[build.processing.html]
  pretty_urls = true

[[headers]]
    # Define which paths this specific [[headers]] block will cover.
    for = "/*"
        [headers.values]
        Access-Control-Allow-Origin = "*"